sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t leslykqi/react-app -f Dockerfile.dev .

script:
    - docker run -e CI=true leslykqi/react-app npm run test