sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t leslykqi/react-app -f Dockerfile.dev .

script:
    - docker run -e CI=true leslykqi/react-app npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "react-app"
    env: "ReactApp-env"
    bucket_name: "elasticbeanstalk-us-east-1-925348302516"
    bucket_path: "react-app"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY